FROM ghcr.io/helmfile/helmfile:latest

MAINTAINER Pavlo Daniv <pauldaniv@gmail.com>
LABEL org.opencontainers.image.source=https://github.com/pauldaniv/yellow-taxi-scripts

RUN apk add --update aws-cli

WORKDIR /home/root

CMD ["/bin/bash"]
