# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build Containers

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
#      - name: Install dependencies
#        run: |
#          sudo apt-get -y update
#          sudo apt-get -y upgrade
#          sudo apt-get -y install screen awscli

      - name: Log into GitHub registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
        run: echo $GITHUB_TOKEN | docker login ghcr.io -u ${GITHUB_USER:-${{ github.actor }}} --password-stdin

      - name: Build
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: bash bin/build_images.sh
