# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build Containers

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

permissions:
  packages: write

jobs:
  list-images:
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.set-images.outputs.images }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Images for later
        id: set-images
        run: echo "images=$(ls src | grep -v base | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  build-and-push-base:
    needs: list-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log into GitHub registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
        run: echo $GITHUB_TOKEN | docker login ghcr.io -u ${GITHUB_USER:-${{ github.actor }}} --password-stdin
      - name: Set permission
        run: chmod -R +x bin
      - name: Build image
        run: ./bin/build_image base
      - name: Deploy to GitHub if on main branch
        if: github.ref == 'refs/heads/main'
        run: ./bin/push_image base

  build-and-push-images:
    needs: [build-and-push-base, list-images]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ${{ fromJson(needs.list-images.outputs.images) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log into GitHub registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
        run: echo $GITHUB_TOKEN | docker login ghcr.io -u ${GITHUB_USER:-${{ github.actor }}} --password-stdin
      - name: Set permission
        run: chmod -R +x bin
      - name: Build image
        run: ./bin/build_image ${{ matrix.image }}
      - name: Deploy to GitHub if on main branch
        if: github.ref == 'refs/heads/main'
        run: ./bin/push_image ${{ matrix.image }}
